# 104API爬蟲

In [113]:
import requests
import json
import re
import csv
from bs4 import BeautifulSoup
import time

# 視覺化
import matplotlib.pyplot as plt
import pandas as pd # 引用套件並縮寫為 pd  

from pandas import Series, DataFrame 

job_url = 'http://www.104.com.tw/i/apis/jobsearch.cfm?kws={}&kwop=3&fmt=8&cols=JOB,JOB_ADDR_NO_DESCRIPT,DESCRIPTION,JOBSKILL_ALL_DESC,PCSKILL_ALL_DESC,APPEAR_DATE,NAME'
jobs = []

In [84]:
from sqlalchemy import create_engine
#create_engine("資料庫類型+資料庫驅動://資料庫用戶名: 資料庫密碼@IP地址:PORT號/資料庫名"，其他参数)
the_connect = create_engine('mysql+pymysql://root:754612@127.0.0.1:3306/104JOB?charset=utf8')

In [73]:
import pymysql
from sqlalchemy import create_engine
conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='754612', use_unicode=True, charset='utf8')
cur = conn.cursor()

In [76]:
cur.execute('CREATE DATABASE 104JOB ')
cur.execute('USE 104JOB')
conn.commit()

In [2]:
def get_list_page(jobname,number):
    for page in range(1,number):
        url = job_url.format(jobname)
        resp = requests.get(url + '&page=' + str(number))
        job_data = resp.json()['data']
        jobs.extend(job_data)                               
        time.sleep(1.5)

In [111]:
#總共幾頁列表
def get_totalpage(jobname):
    url = job_url.format(jobname)
    total = int(re.findall('"TOTALPAGE":"(\d+)"',requests.get(url).text)[0])
    return total

In [112]:
get_totalpage('軟體工程師')

3667

In [3]:
get_list_page('軟體工程師',50)

In [98]:
joblist ={ }
joblist['TITLE'] = []
joblist['COMPANY'] = []
joblist['AREA'] = []
joblist['SKILL'] = []
joblist['DATE'] = []

In [108]:
cur.execute("""CREATE TABLE TEST (
TITLE VARCHAR(500),
COMPANY VARCHAR(500),
AREA VARCHAR(500),
SKILL VARCHAR(500),
DATE VARCHAR(500)
)""")

0

In [99]:
for row in jobs:
    if 'JOBSKILL_ALL_DESC' not in row:
        row['JOBSKILL_ALL_DESC'] =''
    if 'PCSKILL_ALL_DESC' not in row:
        row['PCSKILL_ALL_DESC'] = ''
for row in jobs:        
        joblist['TITLE'].append(row['JOB'])
        joblist['COMPANY'].append(row['NAME'])
        joblist['AREA'].append(row['JOB_ADDR_NO_DESCRIPT'])
        joblist['SKILL'].append(row['PCSKILL_ALL_DESC'])
        joblist['DATE'].append(row['APPEAR_DATE'])

In [100]:
jobdf =DataFrame(joblist)

In [101]:
jobdf

,AREA,COMPANY,DATE,SKILL,TITLE
0,台北市內湖區,聖森股份有限公司,20180131,ASP ASP.NET ETL MS SQL MySQL HTML JavaScript j...,.NET工程師
1,台北市信義區,聖森股份有限公司,20180131,,DBA 資料庫工程師 (熟MS SQL)
2,台北市內湖區,聖森股份有限公司,20180131,RPG AS/400,AS400 RPG 系統分析工程師
3,台北市信義區,聖森股份有限公司,20180131,MS SQL,系統分析師(SA)
4,台北市大安區,聖森股份有限公司,20180131,,國內業務人員
5,台北市信義區,聖森股份有限公司,20180131,,專案企劃執行經理
6,台北市大安區,聖森股份有限公司,20180131,,特別助理
7,高雄市左營區,聖森股份有限公司,20180131,Excel PowerPoint Word,招募專員(HR Specialist – Recruiter)(高雄)
8,台北市大安區,聖森股份有限公司,20180131,Excel PowerPoint Word,招募專員(HR Specialist – Recruiter)(台北)
9,彰化縣線西鄉,新力美科技股份有限公司,20180131,,工程師(彰濱廠環保部)
10,台北市大安區,中華元田會計師事務所,20180131,,會計師
11,台北市信義區,科倫數碼股份有限公司,20180131,Linux PHP JavaScript,Web Backend Developer (網站後端開發工程師)
12,台北市信義區,科倫數碼股份有限公司,20180131,DHTML HTML JavaScript,Web Frontend Developer (網站前端開發工程師)
13,桃園市中壢區,簾藝窗簾行,20180131,,工程安裝人員
14,新北市中和區,恒通股份有限公司,20180131,,品保助理工程師
15,新北市中和區,恒通股份有限公司,20180131,Excel Word,品管助理工程師
16,新北市中和區,恒通股份有限公司,20180131,,FPC品保工程師/品保部
17,新北市中和區,恒通股份有限公司,20180131,Excel Word AutoCAD CAM,軟板助理工程師/工程開發部
18,新北市中和區,恒通股份有限公司,20180131,Excel Word,網版備料員
19,新北市中和區,恒通股份有限公司,20180131,Excel Word,工程生技部文書人員
20,台北市內湖區,聖森股份有限公司,20180131,ASP ASP.NET ETL MS SQL MySQL HTML JavaScript j...,.NET工程師
21,台北市信義區,聖森股份有限公司,20180131,,DBA 資料庫工程師 (熟MS SQL)
22,台北市內湖區,聖森股份有限公司,20180131,RPG AS/400,AS400 RPG 系統分析工程師
23,台北市信義區,聖森股份有限公司,20180131,MS SQL,系統分析師(SA)
24,台北市大安區,聖森股份有限公司,20180131,,國內業務人員
25,台北市信義區,聖森股份有限公司,20180131,,專案企劃執行經理
26,台北市大安區,聖森股份有限公司,20180131,,特別助理
27,高雄市左營區,聖森股份有限公司,20180131,Excel PowerPoint Word,招募專員(HR Specialist – Recruiter)(高雄)
28,台北市大安區,聖森股份有限公司,20180131,Excel PowerPoint Word,招募專員(HR Specialist – Recruiter)(台北)
29,彰化縣線西鄉,新力美科技股份有限公司,20180131,,工程師(彰濱廠環保部)
...,...,...,...,...,...
150,台北市大安區,中華元田會計師事務所,20180131,,會計師
151,台北市信義區,科倫數碼股份有限公司,20180131,Linux PHP JavaScript,Web Backend Developer (網站後端開發工程師)
152,台北市信義區,科倫數碼股份有限公司,20180131,DHTML HTML JavaScript,Web Frontend Developer (網站前端開發工程師)
153,桃園市中壢區,簾藝窗簾行,20180131,,工程安裝人員
154,新北市中和區,恒通股份有限公司,20180131,,品保助理工程師
155,新北市中和區,恒通股份有限公司,20180131,Excel Word,品管助理工程師
156,新北市中和區,恒通股份有限公司,20180131,,FPC品保工程師/品保部
157,新北市中和區,恒通股份有限公司,20180131,Excel Word AutoCAD CAM,軟板助理工程師/工程開發部
158,新北市中和區,恒通股份有限公司,20180131,Excel Word,網版備料員
159,新北市中和區,恒通股份有限公司,20180131,Excel Word,工程生技部文書人員
160,台北市內湖區,聖森股份有限公司,20180131,ASP ASP.NET ETL MS SQL MySQL HTML JavaScript j...,.NET工程師
161,台北市信義區,聖森股份有限公司,20180131,,DBA 資料庫工程師 (熟MS SQL)
162,台北市內湖區,聖森股份有限公司,20180131,RPG AS/400,AS400 RPG 系統分析工程師
163,台北市信義區,聖森股份有限公司,20180131,MS SQL,系統分析師(SA)
164,台北市大安區,聖森股份有限公司,20180131,,國內業務人員
165,台北市信義區,聖森股份有限公司,20180131,,專案企劃執行經理
166,台北市大安區,聖森股份有限公司,20180131,,特別助理
167,高雄市左營區,聖森股份有限公司,20180131,Excel PowerPoint Word,招募專員(HR Specialist – Recruiter)(高雄)
168,台北市大安區,聖森股份有限公司,20180131,Excel PowerPoint Word,招募專員(HR Specialist – Recruiter)(台北)
169,彰化縣線西鄉,新力美科技股份有限公司,20180131,,工程師(彰濱廠環保部)
170,台北市大安區,中華元田會計師事務所,20180131,,會計師
171,台北市信義區,科倫數碼股份有限公司,20180131,Linux PHP JavaScript,Web Backend Developer (網站後端開發工程師)
172,台北市信義區,科倫數碼股份有限公司,20180131,DHTML HTML JavaScript,Web Frontend Developer (網站前端開發工程師)
173,桃園市中壢區,簾藝窗簾行,20180131,,工程安裝人員
174,新北市中和區,恒通股份有限公司,20180131,,品保助理工程師
175,新北市中和區,恒通股份有限公司,20180131,Excel Word,品管助理工程師
176,新北市中和區,恒通股份有限公司,20180131,,FPC品保工程師/品保部
177,新北市中和區,恒通股份有限公司,20180131,Excel Word AutoCAD CAM,軟板助理工程師/工程開發部
178,新北市中和區,恒通股份有限公司,20180131,Excel Word,網版備料員
179,新北市中和區,恒通股份有限公司,20180131,Excel Word,工程生技部文書人員

In [110]:
jobdf.to_sql("TEST", the_connect,if_exists='append',index=False)